name: Typst Formatting

on: 
  [push, pull_request]

jobs:
  typstyle:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        ref: ${{ github.head_ref }}
    - name: Run typstyle
      uses: typstyle-rs/typstyle-action@main